### ISSUE TITLE
如何保证this.barrageList这个数组的长度为6？

### ISSUE THREAD

**Issue by Okswwen** [superhos/vue-baberrage#10]
使用this.barrageList.push(),不断添加到数组中，setInterval(),定时执行这个方法，会不断地给数组添加数据，随后数组会越来越大，咋保证数组长度就为6，新添加一个后，删除原先的！谢谢

**Comment by superhos** [comment]
实际上barrageList的作用更像是一个任务队列，当新的弹幕消息加入到队列之后，弹幕handler会定时在队列中取出消息进行渲染。所以barrageList在增加的同时也是在消费的。

**Comment by Okswwen** [comment]
定时任务跑，这个数组会越来越大，数据越来越多，弹幕会越来越庞大，咋能限制到：就固定几条，比如：6条！

**Comment by superhos** [comment]
如果限定消费能力的话（例如只能6条），队列肯定无可避免越来越大的。放到现实场景里面这个就是业务方面需要考虑的问题，例如一个火爆的视频单位时间（例如一秒）内有1000条弹幕，实际弹幕舞台只能一秒内只够显示100条，那么就必须先通过一定的业务逻辑算法从这1000条弹幕中选出100条的，然后再放到消费队列中。
这里的barrageList只保证防止有突然大流量进入的时候渲染爆炸，如果要具体限定6条的话，只能在push之前确定可进入的数量了。

**Comment by Okswwen** [comment]
ok，了解，感谢解答！
