### ISSUE TITLE
pause 和 replay是有问题的

### ISSUE THREAD

**Issue by shangxinbo** [superhos/vue-baberrage#14]
我尝试调用pause和replay方法，发现这两个方法是不起作用的，pause方法里是不是应该清除一下taskQueque而不是仅仅清除fameId

**Comment by superhos** [comment]
pause的意思是暂停，弹幕会停止动画，但不会清除弹幕，这是供后面版本弹幕事件处理配合使用的。
Thanks for your feedback.
