### ISSUE TITLE
barrageList放在Vuex中 有很多bug ，好像没怎么测试吧。

### ISSUE THREAD

**Issue by ben-Run** [superhos/vue-baberrage#17]
两步即可，当有新的数据加入到barrageList，就会以弹幕形式展现出来，建议barrageList放在Vuex中。? 放进去有很多的bug, 时灵时不灵。
```
 ...mapGetters('base', {
      barrageList: 'barrageList'
    }),
```
版本："vue-baberrage": "^2.1.9",

**Comment by superhos** [comment]
Have been marked down. Will fix in next version. Thanks for your feedback.
