### ISSUE TITLE
hoverLanePause 出现的 BUG

### ISSUE THREAD

**Issue by HeLuchao** [superhos/vue-baberrage#24]
v3.2.4 版本hoverLanePause: true鼠标 hover的时候弹幕泳道未暂停滚动

**Comment by superhos** [comment]
该功能在该版本暂未实现，只是预留了接口。会在近期版本开发，感谢关注！

**Comment by Liangrr** [comment]
现在有预留暂停接口吗？可以加点赞功能吗
