### ISSUE TITLE
基于vue-baberrage开发的一款产品

### ISSUE THREAD

**Issue by tsingliuwin** [superhos/vue-baberrage#25]
https://light.kaoyanvip.cn
期待plus，可以增加更多功能

**Comment by superhos** [comment]
非常棒！
plus一直在构思，无奈一个人时间太有限了，有兴趣的话可以后面共同开发。

**Comment by tsingliuwin** [comment]
> 非常棒！
> plus一直在构思，无奈一个人时间太有限了，有兴趣的话可以后面共同开发。

可以的。
目前我们的产品还有一个bug，打开页面弹幕正常滚动，但是熄屏一段时间后再看，弹幕就会拥挤在一起。
