### ISSUE TITLE
拼错一个字母

### ISSUE THREAD

**Issue by djmaxwow** [superhos/vue-baberrage#27]
demo链接和文档中拼错字母，让我以为在npm包中也是babar
https://blog.chenhaotaishuaile.com/vue-baberrage/ 正确
https://blog.chenhaotaishuaile.com/vue-babarrage/ 错误
之前我因此装vue-bab**a**rrage 结果导致提示404

**Comment by superhos** [comment]
非常感谢，之前的名字是baba，感觉有点叫爸爸的感觉所以改成了babe亲切点，文档没有同步更新到，感谢指出。

**Comment by djmaxwow** [comment]
> 非常感谢，之前的名字是baba，感觉有点叫爸爸的感觉所以改成了babe亲切点，文档没有同步更新到，感谢指出。

666，组件写的不错
