### ISSUE TITLE
如何控制每条泳道的高度呢？弹幕高度boxHeight设置失败？如何能把弹幕position到手机屏幕的中间位置呢，用position弹幕就失效了？

### ISSUE THREAD

**Issue by Lixu-a** [superhos/vue-baberrage#29]
使用vue开发，H5项目
如何控制每条泳道的高度呢？弹幕高度boxHeight设置失败？如何能把弹幕position到手机屏幕的中间位置呢，用position弹幕就失效了？

**Comment by Lixu-a** [comment]
"vue-baberrage": "^3.2.4"版本的

**Comment by superhos** [comment]
position在之前版本暂时已经废弃，会考虑加入到后续的开发计划中
