### ISSUE TITLE
弹幕会重合在一起，怎么解决

### ISSUE THREAD

**Issue by PengZhao12** [superhos/vue-baberrage#32]
大佬，您好，您这个组件用起来还是挺好的，就是我这里弹幕会重合在一起，感觉上并不太完美
![image](https://user-images.githubusercontent.com/20991350/78421836-7abe9c80-768d-11ea-9d6a-660270ae3001.png)

![微信图片_20200404155630](https://user-images.githubusercontent.com/20991350/78421817-41862c80-768d-11ea-9dd2-66c9ba6c8f60.png)

**Comment by superhos** [comment]
可以暂时在消息中设置`extraWidth`来增加单条弹幕的额外宽度。
后续再具体修复。
感谢使用！

**Comment by wuhuanju** [comment]
> 可以暂时在消息中设置`extraWidth`来增加单条弹幕的额外宽度。 后续再具体修复。 感谢使用！

但是每条消息的宽度都不是固定的啊，这个extraWidth到底要设置成什么值
