### ISSUE TITLE
一个比较严重的问题：传入的数据列表会被清空

### ISSUE THREAD

**Issue by chua1989** [superhos/vue-baberrage#36]
<vue-baberrage :barrageList="vueBarrageList"></vue-baberrage>

理论上来说barrageList数据作为props数据，是不能去更改的。但是组件在使用这个属性之后将数据清空了。导致父组件中vueBarrageList拿不到值了

**Comment by superhos** [comment]
是的，从props单向数据流的设计下的确不应该修改props数据本身。组件设计的本身目的是想在父子组件间建立一个Pipe管道，数据一旦被读走，便不在管道中存在，不可反复读取。因此对于弹幕数据的管理，目前阶段建议另外存储管理。后续会改用其他方式来传递数据，保证props的单向纯粹性。
Thanks for your suggestion!
