### ISSUE TITLE
是否可以通过样式增加性能

### ISSUE THREAD

**Issue by wll8** [superhos/vue-baberrage#4]
从下面的图片看起来， 弹幕的移动是通过 js 不断修改 transform 属性。
![image](https://user-images.githubusercontent.com/28223260/49979707-26b91180-ff8b-11e8-8ccf-03e8beb3341c.png)

这样会导致 dom 频繁更新， 导致部分手机卡顿。
如果就移动位置而言， 是不是由 js 设置初始位置和目标位置就好了？ 移动由 css 去做？

**Comment by superhos** [comment]
使用JS是因为考虑到中间会加入交互性的操作，CSS动画版本的话在分支版本有实现，另外最新的版本已经开发尾声阶段了，有针对于性能上的优化，欢迎之后继续使用。

**Comment by wll8** [comment]
楼主威武， 这么晚还没睡， 楼主辛苦了。
期待你的大作。

**Comment by superhos** [comment]
HAHA.
Many thanks and good night.
