### ISSUE TITLE
如果弹幕数量过多会有问题吗？

### ISSUE THREAD

**Issue by 1100100** [superhos/vue-baberrage#51]
如果弹幕数量过多会有问题吗？比如内存不够用，或浏览器卡死崩溃

**Comment by superhos** [comment]
目前组件的目标是方便弹幕的展示，因此弹幕数量的控制实际上不在开发的初衷和目标上，该部分需要使用者从弹幕来源中进行限制，例如一秒实际弹幕可能上千条，随机过滤30条来进行展示。
