### ISSUE TITLE
关于性能问题建议

### ISSUE THREAD

**Issue by 1100100** [superhos/vue-baberrage#52]
这两天有一个小项目，需要做弹幕，时间比较赶，就用了这个插件，用了发现性能不太好，19年的mac,i9CPU，能飙到30%多，本来想着聚凑合用了，后来因为需求变了，逻辑比较特别，这个插件实现不了，就只能自己简单写一个能满足需求的简易版，发现性能还行，至少对CPU不会有很明显的消耗，我分析了一下你的原码，性能应该是消耗在了弹幕滚动moveTo函数那里，我建议是别用js来实时计算位置，而是提前计算好要移动的具体（大概是屏幕宽度吧），利用css的animation来实现滚动，利用对象的animationend回调事件来处理弹幕滚动结束的逻辑，目前我是这么实现的，性能提升了很多，但是我只是很简易的做了一个东西，可能考虑不周全，仅供参考

**Comment by superhos** [comment]
目前项目是有css实现的分支的，主分支使用js控制的考虑是更方便添加相关的独立事件，幸运的是css新规范中也开始提供动画进行中的相关事件，后续会考虑放弃对旧版本浏览器的支持，全面使用新规范的css动画实现。

Thanks for your recommend!
