### ISSUE TITLE
vue.js引用方式

### ISSUE THREAD

**Issue by chaoyang-Rex** [superhos/vue-baberrage#6]
可以不用VUE全家桶的方式引用吗？直接用vue.js方式引用项目？用这种方式怎么引用呢？有文档步骤吗？

**Comment by superhos** [comment]
Sorry for the late reply.

不太了解vue.js方式引用的意思。

CommonJs的模式可以：
`const VueBaberrage = require('vue-baberrage')`
ES6模式可以
`import VueBaberrage from 'vue-baberrage'`
Browser模式可以使用[unpkg](https://unpkg.com/)的服务来引用JS资源

如果需要支持其他的模块机制，可以pull down项目然后修改相关的打包设置再rebuild一次。

BTW,  插件也没有使用到Vue全家桶其他的插件，只是基于Vue.js开发的插件。

最后，非常感谢关注和使用。
