### ISSUE TITLE
弹幕出来的顺序不够随机啊

### ISSUE THREAD

**Issue by kang558** [superhos/vue-baberrage#63]
弹幕出来的顺序不够随机啊，太有规律了。

**Comment by superhos** [comment]
插件只聚焦在展示效果上，数据的处理实际上已经交还给开发者了。建议可以在放入弹幕队列之前对数据做一个洗牌，让弹幕随机了再放进弹幕队列

**Comment by kang558** [comment]
> 插件只聚焦在展示效果上，数据的处理实际上已经交还给开发者了。建议可以在放入弹幕队列之前对数据做一个洗牌，让弹幕随机了再放进弹幕队列

不是，我的意思是出来的位置不够随机，现在都是按从上到下出来的，一排一排的不够随机
