### ISSUE TITLE
在push新内容时，弹幕会出现在其他位置

### ISSUE THREAD

**Issue by dongH555** [superhos/vue-baberrage#9]
![WeChat79f393ee6202bb2c819948b6aec0efef](https://user-images.githubusercontent.com/31405731/61790802-c5bfb900-ae4a-11e9-9dc1-238b33815247.png)

**Comment by anzi-Zhang** [comment]
11

**Comment by superhos** [comment]
应该是由于push内容的时候弹幕区域宽高发生变化引起，后续版本解决。
